-- Report 4: Target Tracking
SELECT
  d.SETTLEMENTDATE,
  d.INITIALMW,
  d.TOTALCLEARED,
  TRY_DIVIDE((d.TOTALCLEARED - d.INITIALMW), NULLIF(d.INITIALMW, 0)) * 100 AS pct_variance
FROM
  `external_data`.`nemweb`.`silver_next_day_dispatch_dispatch_unit_solution` d
WHERE
  d.DUID = 'YABULU'
  AND d.SETTLEMENTDATE >= DATE_SUB(CURRENT_DATE, 13)
  AND d.SETTLEMENTDATE < DATE_ADD(CURRENT_DATE, 1)
  AND d.INITIALMW IS NOT NULL
  AND d.TOTALCLEARED IS NOT NULL
ORDER BY
  d.SETTLEMENTDATE ASC
LIMIT 5000
